import{a as g,i as m,S as p}from"./assets/vendor-Qob_5Ba8.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))a(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const i of t.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&a(i)}).observe(document,{childList:!0,subtree:!0});function o(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function a(e){if(e.ep)return;e.ep=!0;const t=o(e);fetch(e.href,t)}})();const b="46845751-23df18a8b1d1a4c3ff293bf75",w="https://pixabay.com/api/";async function f(s,r=1,o=15){const a=`${w}`;try{const e=await g.get(a,{params:{key:b,q:s,image_type:"photo",orientation:"horizontal",safesearch:!0,page:r,per_page:o}});if(e.data.hits.length===0)throw new Error("No images found");return e.data}catch(e){throw console.error("Error fetching images:",e),e}}function h(s){const r=document.querySelector(".gallery");r&&(r.innerHTML=s.map(o=>`
        <a href="${o.largeImageURL}" class="gallery__link">
            <div class="gallery__item">
                <img src="${o.webformatURL}" alt="${o.tags}" loading="lazy" />
                <div class="gallery__info">
                    <p><b>Likes:</b> ${o.likes}</p>
                    <p><b>Views:</b> ${o.views}</p>
                    <p><b>Comments:</b> ${o.comments}</p>
                    <p><b>Downloads:</b> ${o.downloads}</p>
                </div>
            </div>
        </a>
    `).join(""))}function L(){const s=document.querySelector(".gallery");s&&(s.innerHTML="")}function c(s){m.error({title:"Error",message:s,position:"topRight"})}function d(s){const r=document.querySelector(".loader");r&&(r.style.display=s?"block":"none")}document.addEventListener("DOMContentLoaded",()=>{const s=document.querySelector(".search-form"),r=document.querySelector(".load-more"),o=new p(".gallery a");let a=1,e="";const t=15,i=()=>r.style.display="none",u=()=>r.style.display="block";s.addEventListener("submit",async n=>{if(n.preventDefault(),e=n.currentTarget.elements.searchQuery.value.trim(),e===""){c("Please enter a search query");return}L(),d(!0),i(),a=1;try{const l=await f(e,a,t);!l.hits||l.hits.length===0?c("Sorry, there are no images matching your search query. Please try again!"):(h(l.hits),o.refresh(),l.totalHits>t&&u())}catch{c("An error occurred while fetching images. Please try again later.")}finally{d(!1)}}),r.addEventListener("click",async()=>{a+=1,d(!0),i();try{const n=await f(e,a,t);if(n.hits&&n.hits.length>0)if(h(n.hits,!0),o.refresh(),a*t>=n.totalHits)c("We're sorry, but you've reached the end of search results.");else{u();const{height:y}=document.querySelector(".gallery").firstElementChild.getBoundingClientRect();window.scrollBy({top:y*2,behavior:"smooth"})}else c("We're sorry, but you've reached the end of search results.")}catch{c("An error occurred while loading more images. Please try again.")}finally{d(!1)}})});
//# sourceMappingURL=index.js.map
