import{a as m,S as g,i as b}from"./assets/vendor-Qob_5Ba8.js";(function(){const n=document.createElement("link").relList;if(n&&n.supports&&n.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))t(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const s of r.addedNodes)s.tagName==="LINK"&&s.rel==="modulepreload"&&t(s)}).observe(document,{childList:!0,subtree:!0});function a(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function t(e){if(e.ep)return;e.ep=!0;const r=a(e);fetch(e.href,r)}})();const L="46845751-23df18a8b1d1a4c3ff293bf75",w="https://pixabay.com/api/";async function p(c,n=1,a=15){try{return(await m.get(w,{params:{key:L,q:c,image_type:"photo",orientation:"horizontal",safesearch:!0,page:n,per_page:a}})).data}catch(t){throw console.error("Error fetching images:",t),t}}function y(c){const n=document.querySelector(".gallery"),a=c.map(t=>`
    <li class="gallery__item">
      <a href="${t.largeImageURL}">
        <img src="${t.webformatURL}" alt="${t.tags}" loading="lazy"/>
        <div class="gallery__info">
          <p><b>Лайки:</b> ${t.likes}</p>
          <p><b>Перегляди:</b> ${t.views}</p>
          <p><b>Коментарі:</b> ${t.comments}</p>
          <p><b>Завантаження:</b> ${t.downloads}</p>
        </div>
      </a>
    </li>
  `).join("");n.insertAdjacentHTML("beforeend",a)}function v(){document.querySelector(".gallery").innerHTML=""}document.addEventListener("DOMContentLoaded",()=>{const c=document.querySelector(".form"),n=document.querySelector(".load-more"),a=document.getElementById("loader"),t=new g(".gallery a");let e=1,r="";const s=15,u=()=>n.style.display="none",f=()=>n.style.display="block",d=o=>{a.style.display=o?"block":"none"},i=o=>{b.info({title:"",message:o,position:"topRight",timeout:3e3})};c.addEventListener("submit",async o=>{if(o.preventDefault(),r=o.currentTarget.elements.searchQuery.value.trim(),r===""){i("Будь ласка, введіть пошуковий запит");return}v(),d(!0),u(),e=1;try{const l=await p(r,e,s);!l.hits||l.hits.length===0?i("На жаль, немає зображень, що відповідають вашому пошуковому запиту. Спробуйте ще раз!"):(y(l.hits),t.refresh(),l.totalHits>s&&f(),i(`Ура! Ми знайшли ${l.totalHits} зображень.`))}catch{i("Сталася помилка під час отримання зображень. Спробуйте пізніше.")}finally{d(!1)}}),n.addEventListener("click",async()=>{e+=1,d(!0),u();try{const o=await p(r,e,s);if(o.hits&&o.hits.length>0)if(y(o.hits),t.refresh(),e*s>=o.totalHits)i("Вибачте, але ви досягли кінця результатів пошуку.");else{f();const{height:h}=document.querySelector(".gallery").firstElementChild.getBoundingClientRect();window.scrollBy({top:h*2,behavior:"smooth"})}else i("Вибачте, але ви досягли кінця результатів пошуку.")}catch{i("Сталася помилка під час завантаження додаткових зображень. Спробуйте ще раз.")}finally{d(!1)}})});
//# sourceMappingURL=index.js.map
