import{a as f,i as y,S as h}from"./assets/vendor-Qob_5Ba8.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))n(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const s of t.addedNodes)s.tagName==="LINK"&&s.rel==="modulepreload"&&n(s)}).observe(document,{childList:!0,subtree:!0});function o(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function n(e){if(e.ep)return;e.ep=!0;const t=o(e);fetch(e.href,t)}})();const g="46845751-23df18a8b1d1a4c3ff293bf75",m="https://pixabay.com/api/";async function d(a,r=1,o=15){const n=`${m}`;try{const e=await f.get(n,{params:{key:g,q:a,image_type:"photo",orientation:"horizontal",safesearch:!0,page:r,per_page:o}});if(e.data.hits.length===0)throw new Error("No images found");return e.data}catch(e){throw console.error("Error fetching images:",e),e}}function u(a){const r=document.querySelector(".gallery");r&&(r.innerHTML=a.map(o=>`
        <a href="${o.largeImageURL}" class="gallery__link">
            <div class="gallery__item">
                <img src="${o.webformatURL}" alt="${o.tags}" loading="lazy" />
                <div class="gallery__info">
                    <p><b>Likes:</b> ${o.likes}</p>
                    <p><b>Views:</b> ${o.views}</p>
                    <p><b>Comments:</b> ${o.comments}</p>
                    <p><b>Downloads:</b> ${o.downloads}</p>
                </div>
            </div>
        </a>
    `).join(""))}function p(){const a=document.querySelector(".gallery");a&&(a.innerHTML="")}function l(a){y.error({title:"Error",message:a,position:"topRight"})}function c(a){const r=document.querySelector(".loader");r&&(r.style.display=a?"block":"none")}document.addEventListener("DOMContentLoaded",()=>{const a=document.querySelector(".search-form"),r=document.querySelector(".load-more"),o=new h(".gallery a");let n=1,e="";const t=15;a.addEventListener("submit",async s=>{if(s.preventDefault(),e=s.currentTarget.elements.searchQuery.value.trim(),e===""){l("Please enter a search query");return}p(),c(!0),r.style.display="none",n=1;try{const i=await d(e,n,t);i.hits.length===0?l("Sorry, there are no images matching your search query. Please try again!"):(u(i.hits),o.refresh(),i.totalHits>t&&(r.style.display="block"))}catch{l("An error occurred while fetching images. Please try again.")}finally{c(!1)}}),r.addEventListener("click",async()=>{n+=1,c(!0);try{const s=await d(e,n,t);u(s.hits),o.refresh(),n*t>=s.totalHits?(r.style.display="none",l("We're sorry, but you've reached the end of search results.")):window.scrollBy({top:document.querySelector(".gallery").firstElementChild.getBoundingClientRect().height*2,behavior:"smooth"})}catch{l("An error occurred while loading more images. Please try again.")}finally{c(!1)}})});
//# sourceMappingURL=index.js.map
